### ISSUE TITLE
Can´t send notification emails through the second address

### ISSUE THREAD

**Issue by PRizzoNS** [chrodriguez/redmine_per_project_sender#3]
Hi.
I have 2 projects: "test" and "test2", each one with diffrent "project-sender-email" addresses.
For "test", I have "redmine@mydomain.com" and for "test2": redmine2@mydomain.com
The address that I have for email notifications in Redmine (configuration.tml) is "redmine@mydomain".
The problem is when I fetch an issue through "redmine2@mydomain.com", I can see the issue fetched in Redmine but the "sender email" is not delivered.

In Redmine logs I can see: 
..."Rendered mailer/_issue.html.erb (2.2ms)
  Rendered mailer/issue_edit.html.erb within layouts/mailer (4.7ms)
Email delivery error: 501 5.7.1 <redmine2@nuevosiglo.com.uy>... Permission denied

Redirected to http://192.168.27.186/redmine/issues/33
Completed 302 Found in 163ms (ActiveRecord: 18.0ms) 
..."
Thank you in advance.

**Comment by chrodriguez** [comment]
Sorry for my late response.... Are you form Uruguay? If so, we can simply write in spanish (I'm from Argentina)
The error you posted is from your mail server: the mail server seems to be complaining about a syntax error in you email. See http://www.serversmtp.com/en/smtp-error 

Again, sorry for my late answer

**Comment by PRizzoNS** [comment]
Hola Christian. 
Si, somos vecinos! El error que acusa el mail server es que esta intentando autenticar la segunda cuenta (redmine2@mydomain) cuando en Redmine esta configurada la otra cuenta (redmine@mydomain). Por lo que mi pregunta es: como vincula la cuenta de correo saliente el plugin?
Debería usar otro servidor de correo? 
Muchas gracias

**Comment by chrodriguez** [comment]
Entiendo que el FROM es independiente del usuario configurado en redmine para envíos de correos. Por ende, si tu mail server restringe el envío  de mails de un sender diferente al autenticado, vas a tener que ver la forma de usar un smarthost u otra solución

**Comment by PRizzoNS** [comment]
Si! lo había pensado por ese lado, es mas, lo estaba probando hacer desde el mismo servidor donde tengo alojado Redmine (Ubuntu Server). Estuve viendo la forma de redirigir trafico SMTP desde el server y encontré algo asi como "smtp relay" en sendmail para redirigir algunos correos. 
Podría ser una solución útil?

**Comment by chrodriguez** [comment]
Sendmail es un mundo para lo que necesitás. Fijate si [ssmtp](https://wiki.debian.org/sSMTP) no te simplifica la vida

**Comment by PRizzoNS** [comment]
Excelente! voy a interiorizarme mas! 
Muchas gracias Christian!
